{% set name = "types-click-default-group" %}
{% set version = "1.2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-click-default-group-{{ version }}.tar.gz
  sha256: 672a198ab8e13c302c8bdd15908a3bb829a9c91b0cc2be734a86b9f753502e20

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - click >=8.0.0

test:
  commands:
    - test -f $SP_DIR/click_default_group-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for click-default-group
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
    - conda-forge/mypy
