{% set name = "types-click-default-group" %}
{% set version = "1.2.0.20250322" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 565c46cdf58b14b7bbd50bcca3582394f0c4750030a6ad7ae3be032db41fa46d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - click >=8.0.0

test:
  commands:
    - test -f $SP_DIR/click_default_group-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for click-default-group
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
    - conda-forge/mypy
