# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 1.2.0.20250322

package:
  name: types-click-default-group
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/t/types-click-default-group/types_click_default_group-${{ version }}.tar.gz
  sha256: 565c46cdf58b14b7bbd50bcca3582394f0c4750030a6ad7ae3be032db41fa46d

build:
  number: 0
  noarch: python
  script:
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - click >=8.0.0
    - python >=${{ python_min }}

tests:
  - requirements:
      run:
        - pip
    script:
      - pip check
      - test -f $SP_DIR/click_default_group-stubs/__init__.pyi

about:
  summary: Typing stubs for click-default-group
  license: Apache-2.0 AND MIT
  license_file: LICENSE
  homepage: https://github.com/python/typeshed

extra:
  recipe-maintainers:
    - maresb
    - conda-forge/mypy
